name: Hello world
on: workflow_dispatch
jobs:
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - name: Hello step
        run: |
          echo "Welcome to mern stack!"
          echo "Welcome to mern React!"
