name: Input Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the env to deploy
        required: true
        type: choice
        default: dev
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: Choose the git tag to deploy
        required: true
jobs:
    inputs-demo:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy the App
          run: echo "Deploying the ${{inputs.artifact_tag}} to ${{inputs.environment}}"
